In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\\Users\\asarb\\death_rate_from_cardiovascular_disease_age-standardized.csv')

In [3]:
## Death rate per 100 000 mensen
## De eerste 50 rijen bekijken. We gebruiken deze data frame als DIM table voor de dataframe calorieverbruik. 
## Om deze reden zullen we de dataframe alleen opshonen waar nodig en geen verkennende analyse uitvoeren

df.head(50)

,Entity,Code,Year,Age-standardized death rate from cardiovascular diseases among both sexes
0,Afghanistan,AFG,2000,682.15704
1,Afghanistan,AFG,2001,687.93933
2,Afghanistan,AFG,2002,686.98895
3,Afghanistan,AFG,2003,685.59000
4,Afghanistan,AFG,2004,681.61070
5,Afghanistan,AFG,2005,676.28350
6,Afghanistan,AFG,2006,665.86290
7,Afghanistan,AFG,2007,639.72266
8,Afghanistan,AFG,2008,616.12020
9,Afghanistan,AFG,2009,597.43610
10,Afghanistan,AFG,2010,583.21590
11,Afghanistan,AFG,2011,581.76776
12,Afghanistan,AFG,2012,575.00995
13,Afghanistan,AFG,2013,567.20636
14,Afghanistan,AFG,2014,560.07750
15,Afghanistan,AFG,2015,550.87610
16,Afghanistan,AFG,2016,544.42975
17,Afghanistan,AFG,2017,544.43427
18,Afghanistan,AFG,2018,539.16034
19,Afghanistan,AFG,2019,537.93036
20,Afghanistan,AFG,2020,557.55725
21,Afghanistan,AFG,2021,509.72632
22,Africa,OWID_AFR,2000,310.23676
23,Africa,OWID_AFR,2001,311.28940
24,Africa,OWID_AFR,2002,311.56210
25,Africa,OWID_AFR,2003,312.45210
26,Africa,OWID_AFR,2004,307.68240
27,Africa,OWID_AFR,2005,301.79320
28,Africa,OWID_AFR,2006,301.30255
29,Africa,OWID_AFR,2007,299.99725
30,Africa,OWID_AFR,2008,299.61100
31,Africa,OWID_AFR,2009,298.37198
32,Africa,OWID_AFR,2010,298.69970
33,Africa,OWID_AFR,2011,295.06323
34,Africa,OWID_AFR,2012,293.82224
35,Africa,OWID_AFR,2013,287.59363
36,Africa,OWID_AFR,2014,286.54022
37,Africa,OWID_AFR,2015,290.71097
38,Africa,OWID_AFR,2016,285.07812
39,Africa,OWID_AFR,2017,281.49478
40,Africa,OWID_AFR,2018,282.36316
41,Africa,OWID_AFR,2019,281.06550
42,Africa,OWID_AFR,2020,289.85956
43,Africa,OWID_AFR,2021,280.62042
44,Albania,ALB,2000,450.08835
45,Albania,ALB,2001,313.11870
46,Albania,ALB,2002,353.40994
47,Albania,ALB,2003,401.00742
48,Albania,ALB,2004,380.62463
49,Albania,ALB,2005,386.19327

In [4]:
# We maken eerst een copy van de origenele data set

dfbu= df.copy()

In [5]:
dfbu.head()

,Entity,Code,Year,Age-standardized death rate from cardiovascular diseases among both sexes
0,Afghanistan,AFG,2000,682.15704
1,Afghanistan,AFG,2001,687.93933
2,Afghanistan,AFG,2002,686.98895
3,Afghanistan,AFG,2003,685.59000
4,Afghanistan,AFG,2004,681.61070

In [6]:
# controleren of er dubbele waarden zijn. Deze zijn er dus niet

dfbu[dfbu.duplicated()]

Empty DataFrame
Columns: [Entity, Code, Year, Age-standardized death rate from cardiovascular diseases among both sexes]
Index: []

In [7]:
#controleren of er missing values aanwezig zijn. Deze zijn er dus niet

dfbu.isna().any().any()
print(dfbu.isna().sum())

Entity                                                                       0
Code                                                                         0
Year                                                                         0
Age-standardized death rate from cardiovascular diseases among both sexes    0
dtype: int64

In [8]:
##aantal rijen
dfbu.shape

(4422, 4)

In [9]:
dfbu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4422 entries, 0 to 4421
Data columns (total 4 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   Entity                                                                     4422 non-null   object
 1   Code                                                                       4422 non-null   object
 2   Year                                                                       4422 non-null   int64
 3   Age-standardized death rate from cardiovascular diseases among both sexes  4422 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 138.3+ KB

In [10]:
#kolom aanmaken die combinatie is tussen code en jaar om in een later stadium dit bestand te joinen met andere bestanden die 
# een zelfde waarde hebben

dfbu.loc[:,'Code_Year'] = (dfbu['Code'] + '_' + dfbu['Year'].astype(str) )

In [14]:
print(dfbu.columns.tolist())

['Entity', 'Code', 'Year', 'Age-standardized death rate from cardiovascular diseases among both sexes', 'Code_Year']

In [11]:
dfbu.head(10)

,Entity,Code,Year,Age-standardized death rate from cardiovascular diseases among both sexes,Code_Year
0,Afghanistan,AFG,2000,682.15704,AFG_2000
1,Afghanistan,AFG,2001,687.93933,AFG_2001
2,Afghanistan,AFG,2002,686.98895,AFG_2002
3,Afghanistan,AFG,2003,685.59000,AFG_2003
4,Afghanistan,AFG,2004,681.61070,AFG_2004
5,Afghanistan,AFG,2005,676.28350,AFG_2005
6,Afghanistan,AFG,2006,665.86290,AFG_2006
7,Afghanistan,AFG,2007,639.72266,AFG_2007
8,Afghanistan,AFG,2008,616.12020,AFG_2008
9,Afghanistan,AFG,2009,597.43610,AFG_2009

In [12]:
#het dfbu bestand ga ik mergen/joinen met het populatie bestand dat ik in een ander project heb gebruikt
# om zodoende de deathhrate agv hart en vaatziekten en totale populatie op landniveau te kunnen zien.
#welke bestanden zijn er in huidige map

import os

os.listdir()

['.ipynb_checkpoints',
 'calorie_intake.ipynb',
 'cardiovascular_disease.ipynb',
 'cardiovascular_disease_death_rate_age_group.ipynb',
 'population.ipynb']

In [17]:
## het te mergen bestand inladen
df_popbu = pd.read_csv(
    r'C:\\Users\\asarb\\df_pop.csv',
    sep=';')

In [18]:
df_popbu.head()

,Country,Code,Year,Ages 65+,Ages 25-64,Ages 15-24,Ages 5-14,Under-5,Tot_Ages,% 65+,% 25-64,% 15-24,% 5-14,% under 5,Code_Year
0,Afghanistan,AFG,1950,221587,2881749,1481164,1891648,1300032,7776180,3,37,19,24,17,AFG_1950
1,Afghanistan,AFG,1951,225330,2914332,1503397,1931423,1304861,7879343,3,37,19,25,17,AFG_1951
2,Afghanistan,AFG,1952,228860,2948439,1526378,1971722,1312385,7987784,3,37,19,25,16,AFG_1952
3,Afghanistan,AFG,1953,232109,2982329,1548885,2008840,1324540,8096703,3,37,19,25,16,AFG_1953
4,Afghanistan,AFG,1954,235141,3016448,1570535,2043247,1342583,8207954,3,37,19,25,16,AFG_1954

In [19]:

dfbu = dfbu.merge(
    df_popbu[['Code_Year', 'Tot_Ages']],
    on='Code_Year',
    how='left'
)

In [20]:
dfbu.head()

,Entity,Code,Year,Age-standardized death rate from cardiovascular diseases among both sexes,Code_Year,Tot_Ages
0,Afghanistan,AFG,2000,682.15704,AFG_2000,20130329.0
1,Afghanistan,AFG,2001,687.93933,AFG_2001,20284297.0
2,Afghanistan,AFG,2002,686.98895,AFG_2002,21378116.0
3,Afghanistan,AFG,2003,685.59000,AFG_2003,22733044.0
4,Afghanistan,AFG,2004,681.61070,AFG_2004,23560646.0

In [21]:
## death rate from cardiovascular diseases and tot_ages zjn beide float. Ze kunnen berekeningen ondergaar
dfbu.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4422 entries, 0 to 4421
Data columns (total 6 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   Entity                                                                     4422 non-null   object
 1   Code                                                                       4422 non-null   object
 2   Year                                                                       4422 non-null   int64
 3   Age-standardized death rate from cardiovascular diseases among both sexes  4422 non-null   float64
 4   Code_Year                                                                  4422 non-null   object
 5   Tot_Ages                                                                   4390 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 241.8+ KB

In [22]:
##maar eerst de kolomnamen hernoemen
dfbu= dfbu.rename(columns = {'Tot_Ages':'Population'})
dfbu= dfbu.rename(columns = {'Entity':'Country'})
dfbu= dfbu.rename(columns = {'Age-standardized death rate from cardiovascular diseases among both sexes':'Death_rateCVD'})
dfbu.index.name = 'Index'

In [23]:
dfbu.head(10)

           Country Code  Year  Death_rateCVD Code_Year  Population
Index
0      Afghanistan  AFG  2000      682.15704  AFG_2000  20130329.0
1      Afghanistan  AFG  2001      687.93933  AFG_2001  20284297.0
2      Afghanistan  AFG  2002      686.98895  AFG_2002  21378116.0
3      Afghanistan  AFG  2003      685.59000  AFG_2003  22733044.0
4      Afghanistan  AFG  2004      681.61070  AFG_2004  23560646.0
5      Afghanistan  AFG  2005      676.28350  AFG_2005  24404564.0
6      Afghanistan  AFG  2006      665.86290  AFG_2006  25424088.0
7      Afghanistan  AFG  2007      639.72266  AFG_2007  25909839.0
8      Afghanistan  AFG  2008      616.12020  AFG_2008  26482617.0
9      Afghanistan  AFG  2009      597.43610  AFG_2009  27466086.0

In [24]:
#kolom aanmaken die het percentage sterfgevallen aan cardiovasculaire ziektes weergeven
##Het blijkt dat het geen nut heeft death rate te delen door het populatiegetal. Death is al per 100 000 mensen

## onderstaande kolom Perc_DeathRate_CVD vervalt dus
##dfbu['Perc_DeathRate_CVD'] = dfbu['Age-standardized death rate from cardiovascular diseases among both sexes']/ dfbu['Population']

In [25]:
dfbu.head(10)

           Country Code  Year  Death_rateCVD Code_Year  Population
Index
0      Afghanistan  AFG  2000      682.15704  AFG_2000  20130329.0
1      Afghanistan  AFG  2001      687.93933  AFG_2001  20284297.0
2      Afghanistan  AFG  2002      686.98895  AFG_2002  21378116.0
3      Afghanistan  AFG  2003      685.59000  AFG_2003  22733044.0
4      Afghanistan  AFG  2004      681.61070  AFG_2004  23560646.0
5      Afghanistan  AFG  2005      676.28350  AFG_2005  24404564.0
6      Afghanistan  AFG  2006      665.86290  AFG_2006  25424088.0
7      Afghanistan  AFG  2007      639.72266  AFG_2007  25909839.0
8      Afghanistan  AFG  2008      616.12020  AFG_2008  26482617.0
9      Afghanistan  AFG  2009      597.43610  AFG_2009  27466086.0

In [26]:
##Het bestand heeft nu wel missing values in kolom 'Perc_DeathRate_CVD'. Deze regels verwijderen we
dfbuWM = dfbu.dropna()

In [27]:
#controleren of er nog missing values aanwezig zijn. Deze zijn er dus niet

dfbuWM.isna().any().any()
print(dfbuWM.isna().sum())

Country          0
Code             0
Year             0
Death_rateCVD    0
Code_Year        0
Population       0
dtype: int64

In [28]:
dfbuWM['Year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
      dtype=int64)

In [30]:
#top 50 landen met de hoogste gemiddelde death rate vanaf 2020 (laatste jaar waar data voor beschikbaar was)
(dfbuWM[
    dfbuWM['Year']>= 2020
    ]
    .groupby('Country')['Death_rateCVD']
    .mean()
    .sort_values(ascending = False)
    .head(50))

Country
Nauru                       767.635000
Micronesia (country)        569.468800
Maldives                    546.728230
Afghanistan                 533.641785
Vanuatu                     526.871500
Marshall Islands            525.671250
Central African Republic    519.374390
Tuvalu                      505.170415
Solomon Islands             489.591800
Lesotho                     487.778000
Turkmenistan                481.576510
Uzbekistan                  472.007845
Bulgaria                    469.342725
Egypt                       455.711490
Haiti                       446.105420
Philippines                 442.363935
Syria                       427.464615
Moldova                     423.592960
Iraq                        423.036810
Yemen                       419.756140
Ukraine                     416.894715
Kiribati                    406.077515
Niue                        403.283535
Belarus                     399.977125
Morocco                     386.732725
Eritrea                     377.896405
Madagascar                  376.622750
Mozambique                  372.330090
Fiji                        372.128465
Armenia                     368.564870
Sudan                       367.369660
Tajikistan                  364.135775
Sierra Leone                363.788950
Zimbabwe                    360.354965
Laos                        358.365300
Georgia                     356.609315
Albania                     355.083375
Eswatini                    353.000700
Palau                       351.261550
Samoa                       348.877110
Serbia                      339.303315
Indonesia                   337.669435
Kazakhstan                  333.957475
Latvia                      330.521200
Pakistan                    327.945815
Guinea-Bissau               327.569355
Oman                        325.855760
Gambia                      324.859330
Russia                      323.849300
Somalia                     322.310015
Name: Death_rateCVD, dtype: float64

In [32]:
df_CardioVD = dfbuWM.copy()

In [33]:
df_CardioVD.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4390 entries, 0 to 4421
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country        4390 non-null   object
 1   Code           4390 non-null   object
 2   Year           4390 non-null   int64
 3   Death_rateCVD  4390 non-null   float64
 4   Code_Year      4390 non-null   object
 5   Population     4390 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 240.1+ KB

In [34]:
##Alvorens bestand op te slaan als .csv converteren we de death rate en tot populatie per rij naar datatype integer

df_CardioVD['Death_rateCVD'] = df_CardioVD['Death_rateCVD'].astype('int64')
df_CardioVD['Population'] = df_CardioVD['Population'].astype('int64')

In [ ]:
#df_CardioVD.head()

In [36]:
df_CardioVD = df_CardioVD.to_csv(
    r'C:\\Users\\asarb\\df_CardioVD.csv',
    index=False
)

In [40]:
#In totaal 41 regels aan landen
dfbuWM['Country'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Europe', 'Fiji', 'Finland',
       'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Niue', 'North America', 'North Korea',
       'North Macedonia', 'Norway', 'Oceania', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia',
       'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan',
       'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)